### ISSUE TITLE
make local image refs LOCTYPE=OTHER OTHERLOCTYPE=FILE instead of URL

### ISSUE THREAD

**Issue by bertsky** [OCR-D/assets#97]
Since core moved towards keeping remote URLs and distiguishing them from local_filename, we cannot clone workspaces from here anymore:

    ocrd workspace -d /tmp/ocrd-test clone --download repo/assets/data/kant_aufklaerung_1784/data/mets.xml

```
Traceback (most recent call last):
  File "/data/ocr-d/ocrd_all/venv38/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/ocr-d/ocrd_all/core/build/__editable__.ocrd-2.65.0-py3-none-any/ocrd/cli/workspace.py", line 140, in workspace_clone
    workspace = ctx.resolver.workspace_from_url(
  File "/data/ocr-d/ocrd_all/core/build/__editable__.ocrd-2.65.0-py3-none-any/ocrd/resolver.py", line 224, in workspace_from_url
    workspace.download_file(f)
  File "/data/ocr-d/ocrd_all/core/build/__editable__.ocrd-2.65.0-py3-none-any/ocrd/workspace.py", line 215, in download_file
    f.local_filename = self.resolver.download_to_directory(self.directory, f.url, subdir=f.fileGrp, basename=basename)
  File "/data/ocr-d/ocrd_all/core/build/__editable__.ocrd-2.65.0-py3-none-any/ocrd/resolver.py", line 93, in download_to_directory
    raise FileNotFoundError(f"File path passed as 'url' to download_to_directory does not exist: '{url}")
FileNotFoundError: File path passed as 'url' to download_to_directory does not exist: 'OCR-D-IMG/INPUT_0017.tif
```

Explanation is simple: Workspace.download_file cannot apply the `Workspace.baseurl` information, because the FLocat does not present itself as having a `OcrdFile.local_filename` – only a `OcrdFile.url` (that actually is a local path relative to `baseurl`).

**Comment by bertsky** [comment]
oops – that was fixed already – sorry for the noise!
